### ISSUE TITLE
Is this gem still maintained?

### ISSUE THREAD

**Issue by gustavoschmidt** [davidsantiago/perforate#12]
Hi everybody,
I see this gem was last updated a couple of years ago and it uses outdated versions of Clojure and Criterium. Does anyone know the reason?

Cheers

**Comment by davidsantiago** [comment]
I haven't used it personally in a while, and it failed to find any real users as far as I'm aware. I don't actively develop it myself, but I'll take patches and update if someone else wants to move it forward.

**Comment by xsc** [comment]
FWIW, I've been using perforate within a few projects, including some using Clojure 1.8.0 and `criterium` 0.4.4. No problems whatsoever!
