### ISSUE TITLE
passing a path to a file 

### ISSUE THREAD

**Issue by humanitiesNerd** [davidsantiago/perforate#7]
I´d like to benchmark my word counter (here https://github.com/humanitiesNerd/stammtisch )

I´d like to pass the path to the file containing the words to be counted as an argument and I can´t figure out how to do that

Can you hep me ?

Thanks

**Comment by davidsantiago** [comment]
Hm, interesting. I didn't really have this situation in mind when I wrote perforate originally, so I don't think there's any way to get auxiliary data from the command line to the benchmark function. 

However, I think you can get the same basic effect, if you have a small set of files you want to benchmark, by setting up a different goal for each of the files you are interested in, and then selecting the goal you want to benchmark on the command line. Would that suffice for you?

**Comment by humanitiesNerd** [comment]
My situation is a bit different from that

I have a huge file (almost 500 Mb) and 2 different implementations of the word counting 

Possibly in the future I will have some other implementations of the wordo counting

But the file will be the same for all of them

Currently I just hardwired the whole path to the file in the code

but before pushing this onto github I was wondering if something better could be arranged

But I do´t want to press you, if this is not among your use cases, it´s fine, this was just an exploration on my side and I´m keeping this on its own branch

On my master branch I have a common main function that does all the benchmarking

So it´s ok

Thanks anyway
Ciao

**Comment by davidsantiago** [comment]
OK, I see. I actually think this is somewhere that the file argument wouldn't do you much good. When you're benchmarking, you want to compare like-with-like as much as possible. You want to compare (I assume) the word count implementations on the same file, not with different files. For that, I think you'd just want a goal like word-count, and then have all of the cases be the different word count implementations. If you still want the command line args to be available, there might be some way to do that, say, passing them to a defgoal setup function for examination and use in the cases, but I don't have the bandwidth to do that myself right now.
